# Implementación de una técnica de aprendizaje máquina sin el uso de un framework

In [5]:
# Lectura de librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [6]:
# Lectura del dataset "Canada_per_capita_income (1).csv"
data = pd.read_csv("Canada_per_capita_income (1).csv")
datos = pd.DataFrame(data)
datos.head()

   year       income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [7]:
# Impresion del dataset
datos

    year        income
0   1970   3399.299037
1   1971   3768.297935
2   1972   4251.175484
3   1973   4804.463248
4   1974   5576.514583
5   1975   5998.144346
6   1976   7062.131392
7   1977   7100.126170
8   1978   7247.967035
9   1979   7602.912681
10  1980   8355.968120
11  1981   9434.390652
12  1982   9619.438377
13  1983  10416.536590
14  1984  10790.328720
15  1985  11018.955850
16  1986  11482.891530
17  1987  12974.806620
18  1988  15080.283450
19  1989  16426.725480
20  1990  16838.673200
21  1991  17266.097690
22  1992  16412.083090
23  1993  15875.586730
24  1994  15755.820270
25  1995  16369.317250
26  1996  16699.826680
27  1997  17310.757750
28  1998  16622.671870
29  1999  17581.024140
30  2000  18987.382410
31  2001  18601.397240
32  2002  19232.175560
33  2003  22739.426280
34  2004  25719.147150
35  2005  29198.055690
36  2006  32738.262900
37  2007  36144.481220
38  2008  37446.486090
39  2009  32755.176820
40  2010  38420.522890
41  2011  42334.711210
42  2012  42665.255970
43  2013  42676.468370
44  2014  41039.893600
45  2015  35175.188980
46  2016  34229.193630

In [8]:
#Se le asigna a la variable x la columna de 'year'
x = datos['year']
# Se le asigna a la variablr y la columna de 'income'
y = datos['income']

# Crear lista con los hiper-parámetros iniciales (thetas)
theta = [1, 1]
# Cargar el valor del learning rate (alpha) de 0.000001
alpha = 0.0000001
print(x.head())
print(y.head())

0    1970
1    1971
2    1972
3    1973
4    1974
Name: year, dtype: int64
0    3399.299037
1    3768.297935
2    4251.175484
3    4804.463248
4    5576.514583
Name: income, dtype: float64

## Inicio de implementacion del algoritmo de Regresion Lineal

In [18]:
# Crear función lambda para la función de hipótesis
h = lambda x, theta: theta[0] + theta[1] * x
# Calcular el total de muestras a partir de los datos (n)
n = len(x)

In [19]:
for i in range(100):
  delta = []
  deltax = []
  for xi, yi in zip(x,y):
    pred = h(xi,theta)
    delta.append(pred-yi)
    deltax.append((pred-yi)*xi)

  dJt0 = 1/n*sum(delta)
  dJt1 = 1/n*sum(deltax)

  print(dJt0)
  print(dJt1)

    # Actualizar theta0
  theta[0] = theta[0] - alpha*dJt0

    # Actualizar theta1
  theta[1] = theta[1] - alpha*dJt1
  print(theta)

75.60656017084608
-0.03793429694277175
[0.9211053675811636, 9.53076895043009]
75.60656017049915
-0.03793429955840111
[0.9210978069251465, 9.53076895422352]
75.60656017014472
-0.03793430756381217
[0.9210902462691295, 9.530768958016951]
75.60656016979765
-0.037934295674587816
[0.9210826856131126, 9.53076896181038]
75.60656016944708
-0.037934297973171195
[0.9210751249570956, 9.53076896560381]
75.6065601690939
-0.03793430098510803
[0.9210675643010787, 9.53076896939724]
75.60656016874542
-0.03793430114363102
[0.9210600036450618, 9.53076897319067]
75.60656016839548
-0.03793430225329196
[0.921052442989045, 9.530768976984099]
75.60656016803972
-0.03793430431409085
[0.9210448823330282, 9.530768980777529]
75.60656016769312
-0.03793430502744431
[0.9210373216770114, 9.53076898457096]
75.60656016734612
-0.03793430106436953
[0.9210297610209947, 9.53076898836439]
75.60656016699447
-0.037934297180556235
[0.921022200364978, 9.53076899215782]
75.60656016664181
-0.03793430597858226
[0.9210146397089612, 9.53076899595125]
75.60656016629807
-0.0379342978146482
[0.9210070790529447, 9.53076899974468]
75.60656016594658
-0.037934295753849316
[0.9209995183969281, 9.53076900353811]
75.60656016559284
-0.0379343015399385
[0.9209919577409115, 9.53076900733154]
75.60656016524305
-0.037934299479139615
[0.920984397084895, 9.530769011124969]
75.6065601648921
-0.037934300588800554
[0.9209768364288785, 9.530769014918398]
75.60656016454014
-0.03793430597858226
[0.920969275772862, 9.53076901871183]
75.6065601641943
-0.03793429710129474
[0.9209617151168457, 9.53076902250526]
75.60656016384243
-0.037934297180556235
[0.9209541544608293, 9.530769026298689]
75.60656016349404
-0.037934293693050423
[0.9209465938048129, 9.530769030092118]
75.60656016313898
-0.03793430074732354
[0.9209390331487967, 9.530769033885548]
75.60656016279191
-0.03793429924135512
[0.9209314724927804, 9.530769037678978]
75.60656016243902
-0.03793430074732354
[0.9209239118367641, 9.530769041472407]
75.60656016208675
-0.03793431216097892
[0.9209163511807479, 9.530769045265838]
75.6065601617406
-0.0379342997169241
[0.9209087905247317, 9.530769049059268]
75.60656016139097
-0.03793430035101606
[0.9209012298687156, 9.530769052852698]
75.60656016103802
-0.03793430566153628
[0.9208936692126994, 9.530769056646129]
75.606560160691
-0.03793430066806205
[0.9208861085566834, 9.530769060439559]
75.6065601603427
-0.037934299399878114
[0.9208785479006674, 9.530769064232988]
75.60656015999251
-0.03793429694277175
[0.9208709872446513, 9.530769068026418]
75.60656015963994
-0.037934300905846534
[0.9208634265886354, 9.530769071819847]
75.60656015928907
-0.03793430494818281
[0.9208558659326195, 9.530769075613279]
75.60656015894324
-0.037934293296742944
[0.9208483052766036, 9.530769079406708]
75.60656015859004
-0.03793430035101606
[0.9208407446205877, 9.530769083200138]
75.60656015823716
-0.037934296387941276
[0.9208331839645719, 9.530769086993567]
75.60656015789101
-0.037934298686524655
[0.9208256233085561, 9.530769090786997]
75.60656015753564
-0.03793430264959944
[0.9208180626525404, 9.530769094580426]
75.60656015718624
-0.03793430264959944
[0.9208105019965247, 9.530769098373856]
75.60656015683584
-0.03793430138141551
[0.920802941340509, 9.530769102167286]
75.6065601564872
-0.03793430264959944
[0.9207953806844933, 9.530769105960715]
75.60656015613301
-0.037934307008981705
[0.9207878200284777, 9.530769109754146]
75.60656015578662
-0.03793429622941829
[0.9207802593724621, 9.530769113547576]
75.606560155437
-0.03793429884504765
[0.9207726987164465, 9.530769117341006]
75.60656015508249
-0.03793430534449029
[0.920765138060431, 9.530769121134437]
75.60656015473796
-0.037934297893909695
[0.9207575774044156, 9.530769124927867]
75.60656015438988
-0.037934299003570635
[0.9207500167484001, 9.530769128721296]
75.60656015403413
-0.037934307008981705
[0.9207424560923847, 9.530769132514727]
75.60656015368899
-0.037934292266343504
[0.9207348954363693, 9.530769136308157]
75.60656015333959
-0.03793429361378893
[0.920727334780354, 9.530769140101587]
75.6065601529881
-0.03793429163225154
[0.9207197741243387, 9.530769143895016]
75.60656015263544
-0.0379342997169241
[0.9207122134683234, 9.530769147688446]
75.60656015228433
-0.03793430074732354
[0.9207046528123082, 9.530769151481875]
75.60656015193425
-0.037934298686524655
[0.920697092156293, 9.530769155275305]
75.60656015158291
-0.03793430177772299
[0.9206895315002779, 9.530769159068734]
75.60656015123226
-0.037934303679998886
[0.9206819708442627, 9.530769162862164]
75.60656015088202
-0.037934303679998886
[0.9206744101882477, 9.530769166655594]
75.60656015053176
-0.03793431065501051
[0.9206668495322327, 9.530769170449025]
75.6065601501836
-0.03793429916209363
[0.9206592888762176, 9.530769174242455]
75.60656014983257
-0.03793430074732354
[0.9206517282202026, 9.530769178035884]
75.60656014948209
-0.03793429821095568
[0.9206441675641877, 9.530769181829314]
75.60656014913106
-0.03793430558227478
[0.9206366069081727, 9.530769185622745]
75.60656014878275
-0.03793429710129474
[0.9206290462521578, 9.530769189416175]
75.60656014843443
-0.03793429844874017
[0.920621485596143, 9.530769193209604]
75.60656014808093
-0.03793430035101606
[0.9206139249401282, 9.530769197003034]
75.60656014773083
-0.03793430455187534
[0.9206063642841134, 9.530769200796463]
75.60656014738112
-0.03793430074732354
[0.9205988036280986, 9.530769204589893]
75.60656014702886
-0.03793430685045871
[0.920591242972084, 9.530769208383324]
75.60656014668247
-0.03793430566153628
[0.9205836823160692, 9.530769212176756]
75.6065601463354
-0.03793429194929752
[0.9205761216600546, 9.530769215970185]
75.60656014598251
-0.0379342905225906
[0.92056856100404, 9.530769219763615]
75.60656014563217
-0.03793429345526594
[0.9205610003480255, 9.530769223557044]
75.60656014528402
-0.03793429694277175
[0.920553439692011, 9.530769227350474]
75.60656014493036
-0.037934296863510256
[0.9205458790359965, 9.530769231143903]
75.60656014457801
-0.03793430534449029
[0.920538318379982, 9.530769234937335]
75.60656014423225
-0.03793429615015679
[0.9205307577239676, 9.530769238730764]
75.60656014388509
-0.03793429622941829
[0.9205231970679533, 9.530769242524194]
75.60656014352872
-0.037934299082832135
[0.9205156364119389, 9.530769246317623]
75.6065601431791
-0.037934299003570635
[0.9205080757559245, 9.530769250111053]
75.60656014283163
-0.037934298290217175
[0.9205005150999103, 9.530769253904483]
75.60656014247975
-0.03793429519901884
[0.920492954443896, 9.530769257697912]
75.60656014212655
-0.037934306295628245
[0.9204853937878817, 9.530769261491344]
75.60656014178049
-0.03793429765612521
[0.9204778331318676, 9.530769265284773]
75.60656014143179
-0.03793429622941829
[0.9204702724758534, 9.530769269078203]
75.60656014107565
-0.03793430423482935
[0.9204627118198393, 9.530769272871632]
75.6065601407278
-0.03793430177772299
[0.9204551511638253, 9.530769276665062]
75.60656014037738
-0.03793430098510803
[0.9204475905078112, 9.530769280458491]
75.60656014002434
-0.03793430296664542
[0.9204400298517972, 9.530769284251921]
75.6065601396737
-0.03793430597858226
[0.9204324691957833, 9.530769288045352]
75.60656013932841
-0.03793429622941829
[0.9204249085397693, 9.530769291838782]
75.60656013897646
-0.03793429202855902
[0.9204173478837554, 9.530769295632211]
75.60656013862504
-0.03793430035101606
[0.9204097872277416, 9.530769299425641]
75.60656013827463
-0.03793430146067701
[0.9204022265717278, 9.53076930321907]
75.606560137925
-0.03793430375926038
[0.920394665915714, 9.5307693070125]
75.6065601375712
-0.03793430566153628
[0.9203871052597002, 9.530769310805931]
75.60656013722512
-0.03793429932061662
[0.9203795446036865, 9.530769314599361]
75.6065601368782
-0.03793429884504765
[0.9203719839476728, 9.53076931839279]
75.60656013652283
-0.0379343070882432
[0.9203644232916591, 9.530769322186222]
75.60656013617645
-0.037934296070895296
[0.9203568626356455, 9.530769325979652]

## Resultados

In [20]:
#Se creara una lista con diferentes años para poder obtener los diferentes resultados y posteriormente de esos años los que se puedan buscar se hara para comprobar esos resultados
lista_valores = [1963, 1996, 2000, 2001, 2010, 2032, 2049]

#Se crea un for loop para poder pasar la lista con los diferentes valores a probar y conocer las predicciones de dichos años
for j in lista_valores:
    h = theta[0] + (theta[1]*j)
    print("Este es el año de interes:", j, "y este es su valor:", h)

# Verificacion de las predicciones ya existentes
lista_valores_existentes = [1963, 1996, 2000, 2001, 2010]
for k in lista_valores_existentes:
    print(datos[datos['year'].isin([k])])

Este es el año de interes: 1963 y este es su valor: 18709.820543760692
Este es el año de interes: 1996 y este es su valor: 19024.33593151802
Este es el año de interes: 2000 y este es su valor: 19062.45900882194
Este es el año de interes: 2001 y este es su valor: 19071.98977814792
Este es el año de interes: 2010 y este es su valor: 19157.766702081735
Este es el año de interes: 2032 y este es su valor: 19367.443627253288
Este es el año de interes: 2049 y este es su valor: 19529.46670579494
Empty DataFrame
Columns: [year, income]
Index: []
    year       income
26  1996  16699.82668
    year       income
30  2000  18987.38241
    year       income
31  2001  18601.39724
    year       income
40  2010  38420.52289